language: cpp
sudo: false
dist: trusty
compiler: clang
os: linux
ruby: 2.2.0
before_script:
- cmake --version
- bundle install
script:
- bundle exec danger
- cmake -H. -Bbuild
- cd build
- make
- ctest
